### PR TITLE
feat: manage existing Fastly resources with Terraform

### PR DESCRIPTION
**Pull request by lemeurherve**
Part of https://github.com/jenkins-infra/helpdesk/issues/2820

Notes:
- I've removed the [deprecated `geo_headers` setting](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl#nested-schema-for-request_setting) of pkg and plugins (was set to `false` in imported resources)
- I've added some teams in CODEOWNERS, to be discussed? I'll add the appropriate teams to the repo.
- More PRs are coming to set the backend and the pipeline, hence the draft. This PR can be reviewed meanwhile.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by dduportal** [comment]
> Code looks good to me!
> 
> I'm blocking becasue the last plan output (https://infra.ci.jenkins.io/job/Terraform%20Jobs/job/fastly/job/PR-1/1/artifact/terraform-plan-for-humans.txt) show that 3 resources will be created once merged

@lemeurherve it sounds like that the current s3 backend  might not have the states that you imported. Did I miss something?

**Comment by lemeurherve** [comment]
Ran `terraform init --migrate-state -backend-config=./backend-config` locally to migrate my local state to the production S3 bucket, and restarted a build, all good now: https://infra.ci.jenkins.io/job/Terraform%20Jobs/job/fastly/job/PR-1/2/artifact/terraform-plan-for-humans.txt

**Comment by lemeurherve** [comment]
I've compared the production versions of the services generated by Terraform with the previous ones defined manually in Fastly interface, I've fixed the diff with [this hotfix](https://github.com/jenkins-infra/fastly/commit/60c9d28ea4035891b1f34260539f42b976c65c31).

**Comment by lemeurherve** [comment]
The hotfix didn't changed anything about the "xff" parameter, still empty in the fastly GUI diff, but since its default value is àppend`it shouldn't make a difference.

**Pull request merged**
